# Site settings
title: Codenhance
tagline: Friendly Coding Lessons for Biologists
email: brian@codenhance.com
description: > # this means to ignore newlines until "baseurl:"
    Friendly coding lessons for biologists
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://codenhance.com" # the base hostname & protocol for your site
twitter_username: codenhance
github_username: codenhance

# Build settings
markdown: kramdown
highlighter: pygments
